### ISSUE TITLE
Component support

### ISSUE THREAD

**Issue by abpetkov** [alexgibson/tap.js#13]
Hi,

I was looking for an alternative to <a href="https://github.com/ftlabs/fastclick">Fastclick</a>, which I'm using for one of my projects, and I came across your plugin. It looks more lightweight and does the same job. And since I have some issues with Fastclick, I decided I may give tap.js a try.

What is a problem for me here, is that you have no <a href="https://github.com/component/component">Component</a> support. So I was wondering if you are up submitting this to the <a href="https://github.com/component/component/wiki/Components">Component registry</a>, so that I can add tap.js as a dependency and use it?

**Comment by alexgibson** [comment]
Closing this, I don't think Component is gaining enough traction.
