### ISSUE TITLE
Maybe document .destroy()

### ISSUE THREAD

**Issue by davidtheclark** [alexgibson/tap.js#24]
Having looked at the code, it seems to me that I should be calling `myTap.destroy()` when I no longer need the tap event ... not just `el.removeEventListener('tap')`. Do you agree?

If so, I think it would be worth documenting this function and its purpose.

**Comment by alexgibson** [comment]
Pull requests are welcome :+1:

**Comment by davidtheclark** [comment]
Cool, just wanted to make sure I wasn't missing the point. PR submitted.

**Comment by alexgibson** [comment]
Thanks again!
