### ISSUE TITLE
What about use-cases other than the click delay?

### ISSUE THREAD

**Issue by davidtheclark** [alexgibson/tap.js#28]
Saw the deprecation notice, and I have a question about it.

My use-case actually was not to eliminate the click delay, but to distinguish a tap from touchstart, which might also be the beginning of a scroll. In https://github.com/davidtheclark/react-aria-menubutton I use it to detect taps outside the open menu (the menu closes when you tap outside it): that's important because if the menu is long enough that you have to scroll to see some items on it, I don't want to close it because you started to scroll.

So I'm wondering: Do you know of some better way to handle this than using tap.js or something like it?

**Comment by alexgibson** [comment]
Feel free to take what code you need for your own use. I don't think it's worth maintaining this library just for edge cases like this, considering how little code there is.

**Comment by davidtheclark** [comment]
Sure, was just wondering if you already had an alternative in mind. Thanks!

**Comment by alexgibson** [comment]
Technically there's also no reason why you can't do this with a regular `click` event now, especially as most browsers are no longer imposing a delay. You can easily enough tell where the event target is to determine if the menu should be closed or not.

**Comment by davidtheclark** [comment]
I will revisit the code and see if that will work. I don't remember the details about why I felt I couldn't do that before.
